-- Vehicle Sales Data --

SELECT * FROM car_sales
;



-- Top 10 Best Selling Makes --

SELECT TOP 10 make, COUNT(saledate_short) AS sales_count
FROM car_sales
GROUP BY make
ORDER BY sales_count DESC
;



-- Sales by State --

SELECT TOP 38 state, COUNT(saledate_short) AS sales_count
FROM car_sales
WHERE state IS NOT NULL
GROUP BY state
ORDER BY sales_count DESC
;



-- Average Sales Price by Mileage --

SELECT 
    CASE 
        WHEN odometer < 10000 THEN '0-10K'
        WHEN odometer BETWEEN 10000 AND 19999 THEN '10K-20K'
        WHEN odometer BETWEEN 20000 AND 29999 THEN '20K-30K'
        WHEN odometer BETWEEN 30000 AND 39999 THEN '30K-40K'
        WHEN odometer BETWEEN 40000 AND 49999 THEN '40K-50K'
        WHEN odometer BETWEEN 50000 AND 59999 THEN '50K-60K'
        WHEN odometer BETWEEN 60000 AND 69999 THEN '60K-70K'
        WHEN odometer BETWEEN 70000 AND 79999 THEN '70K-80K'
        WHEN odometer BETWEEN 80000 AND 89999 THEN '80K-90K'
        WHEN odometer BETWEEN 90000 AND 99999 THEN '90K-100K'
        ELSE '100K+'
    END AS mileage_range,
    AVG(sellingprice) AS average_price
FROM car_sales
GROUP BY 
    CASE 
        WHEN odometer < 10000 THEN '0-10K'
        WHEN odometer BETWEEN 10000 AND 19999 THEN '10K-20K'
        WHEN odometer BETWEEN 20000 AND 29999 THEN '20K-30K'
        WHEN odometer BETWEEN 30000 AND 39999 THEN '30K-40K'
        WHEN odometer BETWEEN 40000 AND 49999 THEN '40K-50K'
        WHEN odometer BETWEEN 50000 AND 59999 THEN '50K-60K'
        WHEN odometer BETWEEN 60000 AND 69999 THEN '60K-70K'
        WHEN odometer BETWEEN 70000 AND 79999 THEN '70K-80K'
        WHEN odometer BETWEEN 80000 AND 89999 THEN '80K-90K'
        WHEN odometer BETWEEN 90000 AND 99999 THEN '90K-100K'
        ELSE '100K+'
    END
ORDER BY mileage_range
;



-- Average Selling Price per Make --

SELECT 
    make, 
    AVG(sellingprice) AS average_selling_price
FROM car_sales
GROUP BY make
ORDER BY average_selling_price DESC
;



-- Popularity by Body Type --

SELECT body, COUNT(saledate_short) AS sales_count
FROM car_sales
WHERE body IS NOT NULL
GROUP BY body
ORDER BY sales_count DESC
;



-- Transmission Types by Percentage --

SELECT 
    transmission, 
    COUNT(saledate_short) AS count_per_type,
    (COUNT(saledate_short) * 100.0 / (SELECT COUNT(saledate_short) FROM car_sales)) AS percentage
FROM car_sales
WHERE transmission IS NOT NULL
GROUP BY transmission
ORDER BY percentage DESC
;



-- Total Revenue Generated by Each Seller --

SELECT 
    seller, 
    SUM(sellingprice) AS total_revenue
FROM car_sales
GROUP BY seller
ORDER BY total_revenue DESC
;



-- Vehicle Models with the Highest Rate of Price Reductions --

SELECT 
    make, 
    COUNT(CASE WHEN mmr > sellingprice THEN 1 END) * 100.0 / COUNT(*) AS price_reduction_rate
FROM car_sales
WHERE make IS NOT NULL
GROUP BY make
ORDER BY price_reduction_rate DESC
;



-- Total Sales Value For Each Month --

SELECT 
    DATEPART(YEAR, saledate_short) AS sale_year,
    DATEPART(MONTH, saledate_short) AS sale_month,
    SUM(sellingprice) AS total_sales_value
FROM car_sales
WHERE sellingprice IS NOT NULL
GROUP BY 
    DATEPART(YEAR, saledate_short), 
    DATEPART(MONTH, saledate_short)
ORDER BY 
    sale_year, 
    sale_month
    ;